version: '3.2'
services:
  app:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    image: yiisoftware/yii2-php:7.4-apache
    container_name: VisorEiasaApp
    restart: unless-stopped
    tty: true
    working_dir: /app/web
    volumes:
      - ./:/app/web
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - app-network-eiasa
    ports:
      - 20080:80
      - 4431:443
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      MYSQL_DATABASE: eiasa_visor
      MYSQL_ROOT_PASSWORD: X0AhfRCK8GMeHfx2
  db:
    image: mariadb:latest
    container_name: VisorEiasaDB
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: eiasa_visor
      MYSQL_ROOT_PASSWORD: X0AhfRCK8GMeHfx2
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network-eiasa
  rabbit:
    image: rabbitmq:3-management
    container_name: VisorRabbitMQ
    restart: unless-stopped
    tty: true
    ports: 
      - 15672:15672
      - 5672:5672
    networks:
      - app-network-eiasa
#Docker Networks
networks:
  app-network-eiasa:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local